services:
  mysql:
    image: mysql:8.4
    container_name: chalet-mysql

    profiles:
      - persistent

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chalet_db

    ports:
      - "2211:3306"

    volumes:
      - mysql-data:/var/lib/mysql_data

    restart: unless-stopped

  mysql-temp:
    image: mysql:8.4
    container_name: chalet-mysql-temp

    profiles:
      - temp

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chalet_db_tmp

    ports:
      - "2212:3306"

  jenkins:
    profiles:
      - ci
    image: jenkins/jenkins:lts-jdk21
    container_name: chalet-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  mysql-data:
  jenkins-data:
