apiVersion: apps/v1
kind: Deployment

metadata:
  name: chalet-core-mysql-deployment

spec:
  replicas: {{ .Values.mysql.replicaCount }}

  selector:
    matchLabels:
      app: chalet-core-mysql

  template:
    metadata:
      labels:
        app: chalet-core-mysql

    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.password | quote }}

            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}

          startupProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -proot

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -proot

          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -uroot
                - -proot

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: chalet-core-mysql-pvc