apiVersion: v1
kind: Service

metadata:
  name: chalet-core-mysql-service

spec:
  selector:
    app: chalet-core-mysql

  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}

  type: {{ .Values.mysql.service.type }}