apiVersion: v1
kind: Service

metadata:
  name: chalet-core-mysql-service

spec:
  selector:
    app: chalet-core-mysql

  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

  type: ClusterIP